# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uitabl.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 779)
        MainWindow.setStyleSheet("QMainWindow {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(43, 117, 255), stop:1 rgb(255, 221, 29));\n"
"}\n"
"\n"
"    ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("centralwidget { background-color: rgb(109, 255, 99) }")
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(5, 0, 0, 0)
                
        self.table_bo = QtWidgets.QFrame(self.centralwidget)
        self.table_bo.setMinimumSize(QtCore.QSize(0, 0))
        self.table_bo.setMaximumSize(QtCore.QSize(16777215, 16777215))
               
        self.verticalLayout = QtWidgets.QVBoxLayout(self.table_bo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
              
        self.frame_4 = QtWidgets.QFrame(self.table_bo)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
              
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
               
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
                
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setMaximumSize(QtCore.QSize(55, 55))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    border: none\n"
"}")
                
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico/til.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setIconSize(QtCore.QSize(35, 35))       
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
          
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        self.label = QtWidgets.QLabel(self.frame_7)        
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)        
        font.setWeight(50)
        self.label.setFont(font)
        self.verticalLayout_5.addWidget(self.label)
        
        self.horizontalLayout_3.addWidget(self.frame_7, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignLeft)

        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(270, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(270, 16777215))
                
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
                
        self.lineEdit = QtWidgets.QLineEdit(self.frame_5)
        
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border-radius:5px;    \n"
"    \n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color:rgb(223, 223, 223)\n"
"}")
        
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)   
        self.horizontalLayout_4.addWidget(self.lineEdit)
                
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(0, 16777215))        
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
                
        self.horizontalLayout_5.setContentsMargins(0, 11, 0, 11)
        self.horizontalLayout_5.setSpacing(7)
        
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_10.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_10.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
    
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ico/back_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon1)
        self.horizontalLayout_5.addWidget(self.pushButton_10)
               
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_11.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_11.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ico/next_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_5.addWidget(self.pushButton_11)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.horizontalLayout_2.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
        
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_6.setMaximumSize(QtCore.QSize(250, 50))
                
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        
            
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 25))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ico/gamburg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(30, 25))      
        self.horizontalLayout_4.addWidget(self.pushButton)
        
        self.line = QtWidgets.QFrame(self.frame_6)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalLayout_4.addWidget(self.line)
        
        self.horizontalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame_4)
        
        self.frame = QtWidgets.QFrame(self.table_bo)
       
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setStyleSheet("QTableWidget {background-color: rgb(235, 235, 235)}")
        
        item_num = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item_num)
        
        item_header1 = QtWidgets.QTableWidgetItem()
        item_header1.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)        
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item_header1.setFont(font)        
        self.tableWidget.setHorizontalHeaderItem(0, item_header1)
        
        item_header2 = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item_header2.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item_header2)
        
        item_header3 = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item_header3.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item_header3)
        
        item_header4 = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item_header4.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item_header4)
        
        item_header5 = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item_header5.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item_header5)
        
        item_header6 = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item_header6.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item_header6)
        
        item_header7 = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item_header7.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item_header7)
         
        self.tableWidget.horizontalHeader().resizeSection(0, 340)
        self.tableWidget.horizontalHeader().resizeSection(1, 320)
        self.tableWidget.horizontalHeader().resizeSection(2, 250)
        self.tableWidget.horizontalHeader().resizeSection(3, 210)
        self.tableWidget.horizontalHeader().resizeSection(4, 150)
        self.tableWidget.horizontalHeader().setSectionResizeMode(5, QtWidgets.QHeaderView.Stretch)
        self.tableWidget.horizontalHeader().resizeSection(6, 50)
        
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.table_bo)
        
        self.frame_2 = QtWidgets.QFrame(self.centralwidget) 
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(0, 9000))
     
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 6, 0)
        
        spacerItem = QtWidgets.QSpacerItem(20, 44, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        self.pushButton_7.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ico/word.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(10, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ico/structure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ico/addperson.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem3)
        
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_12.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        icon4.addPixmap(QtGui.QPixmap("ico/addinfo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon4)
        self.pushButton_12.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12)
        self.verticalLayout_4.addWidget(self.pushButton_12, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem7)
        
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        self.pushButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ico/Edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem4)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        self.pushButton_8.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ico/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon6)
        self.pushButton_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        self.pushButton_6.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ico/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon7)
        self.pushButton_6.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 60))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 60))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border: none\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(41, 198, 255)\n"
"}")
        self.pushButton_4.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ico/server.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon8)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Телефонний довідник"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Пошук..."))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">0</span></p></body></html>"))
        
        item_header1 = self.tableWidget.horizontalHeaderItem(0)
        item_header1.setText(_translate("MainWindow", "Прізвище, ім’я та по батькові"))
        item_header2 = self.tableWidget.horizontalHeaderItem(1)
        item_header2.setText(_translate("MainWindow", "Посада"))
        item_header3 = self.tableWidget.horizontalHeaderItem(2)
        item_header3.setText(_translate("MainWindow", "Міні – АТС внутрішній"))
        item_header4 = self.tableWidget.horizontalHeaderItem(3)
        item_header4.setText(_translate("MainWindow", "Службовий міський"))
        item_header5 = self.tableWidget.horizontalHeaderItem(4)
        item_header5.setText(_translate("MainWindow", "АТС-10"))
        item_header6 = self.tableWidget.horizontalHeaderItem(5)
        item_header6.setText(_translate("MainWindow", "Кабінет"))
        item_header7 = self.tableWidget.horizontalHeaderItem(6)
        item_header7.setText(_translate("MainWindow", "інфо"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        